import { formatDate } from '../utils/authUtils';

/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: 'c0b12fe9-80c6-4247-8ea8-3e10aa3df0fc',
    title: 'The Batman',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Shobit Deshwal',
    videoLink: '',
    likes: 0,
    dislikes: 0,
    views: 0,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4086-aa19-4dc7ed4f0b41',
    title: 'Spiderman: No Way Home',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 10,
    dislikes: 0,
    views: 69,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4086-aa19-4dc7easfw0b41',
    title: 'Avengers: Endgame',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4086-aa19-4ntfsfw0b41',
    title: 'Fantastic Beasts',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action', 'Sci-fi'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4086-aa19-4dcsgwersfw0b41',
    title: 'Man of Steel',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4086-aaghneasfw0b41',
    title: 'Fury',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-wrgwehas-4dc7easfw0b41',
    title: 'Batman Begins',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3baqwertq44086-aa19-4dc7easfw0b41',
    title: 'King Kong',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4wret3qfgqasfw0b41',
    title: 'Me Before You',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Romantic'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1efc-4086-aatiktasfw0b41',
    title: 'Interstellar',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Sci-fi'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-hryjtj-aa19-4dc7easfw0b41',
    title: 'Matrix',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-qwer-4dc7easfw0b41',
    title: 'The Fault in our stars',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Romance', 'Drama'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1sfegwertg9-4dc7easfw0b41',
    title: 'The Pursuit of Happiness',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Drama'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babf0-1ehe5trhr-4dc7easfw0b41',
    title: 'Theory of Everything',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Romance', 'Drama'],
    uploadedAt: formatDate(),
  },
  {
    _id: 'ab3babfregerw6-aa19-4dc7easfw0b41',
    title: '300',
    description:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    creator: 'Marvel',
    videoLink: '',
    likes: 99,
    dislikes: 0,
    views: 10000,
    category: ['Action', 'Drama'],
    uploadedAt: formatDate(),
  },
];
